# Generated by Django 5.1.2 on 2024-10-14 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margin', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('last_modification', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
